# For more info see:
#   https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
#   https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

# Problems deleting the CRD or the related CRs? There is a deadlock problem with "finalizers". See:
#   https://stackoverflow.com/questions/52009124/not-able-to-completely-remove-kubernetes-customresource/52012367#52012367
#   https://github.com/kubernetes/kubernetes/issues/60538

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: runresources.operator.tdaq.cern.ch
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: operator.tdaq.cern.ch
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                label:
                  type: string
                runNumber:
                  type: integer
                  minimum: 0
                runPipe:
                  type: string
            status:
              type: object
              properties:
                isRunFinished:
                  type: boolean
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: runresources
    # singular name to be used as an alias on the CLI and for display
    singular: runresource
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RunResource
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - rr