apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: runresource.operator.tdaq.cern.ch
spec:
  group: operator.tdaq.cern.ch
  version: v1
  scope: Namespaced
  names:
    plural: runresources
    singular: runresource
    kind: RunResource
    shortNames:
      - rr