# For more info see here: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: runresources.operator.tdaq.cern.ch
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: operator.tdaq.cern.ch
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              name: string
              label: string
              runNumber:
                type: integer
                minimum: 0
              runPipe: string
            status:
              isRunFinished: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: runresources
    # singular name to be used as an alias on the CLI and for display
    singular: runresource
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: RunResource
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - rr