apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-tdaq
  namespace: default
spec:
  selector:
    matchLabels:
      app: webserver-tdaq
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver-tdaq
    spec:
      containers:
        - name: webserver-tdaq
          image: persundecern/webserver-tdaq
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m