apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-tdaq
  namespace: default
spec:
  selector:
    matchLabels:
      run: worker-tdaq
  replicas: 1
  template:
    metadata:
      labels:
        run: worker-tdaq
    spec:
      # For a deployment, only "restartPolicy: Always" is supported
      # See: https://github.com/kubernetes/kubernetes/issues/24725
      restartPolicy: Always
      containers:
        - name: worker-tdaq
          image: persundecern/webclient-tdaq
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m