apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
  selector:
    app: webserver


# Can use the values found in Environment Variables
#WEBSERVER_SERVICE_SERVICE_HOST
#WEBSERVER_SERVICE_SERVICE_PORT

#WEBSERVER_SERVICE_SERVICE_HOST=10.96.98.159
#WEBSERVER_SERVICE_SERVICE_PORT=8000